### ISSUE TITLE
What's different with Interpolation Consistency Training(IJCAI 2019)

### ISSUE THREAD

**Issue by t110368027** [hritam-98/ICT-MedSeg#9]
Hi, Thank you for sharing.
I'm reading your paper and reproducing your code.
But your method seems to be highly similar to another method [Interpolation Consistency Training for Semi-Supervised Learning  IJCAI 2019](https://arxiv.org/abs/1903.03825)  [github](https://github.com/vikasverma1077/ICT)
and I also survey to other code reproduced ICT from [SSL4MIS ](https://github.com/HiLab-git/SSL4MIS/commit/c509beb5382a6f98529a30be5a902e6ab9968d74)**_committed on Oct 12, 2020_** .

This code appears to match yours exactly [Compare link](https://www.diffchecker.com/4nFCcbTq/) and contribution earlier than yours [ICT-MedSeg](https://github.com/hritam-98/ICT-MedSeg/commit/44c4d3095b9ed3f83f18213200a55be578564df1) _**committed on Dec 23, 2021**_

I would like to ask if your paper has any new contributions or is it different from [SSL4MIS](https://github.com/HiLab-git/SSL4MIS) reproduced [ICT](https://github.com/HiLab-git/SSL4MIS/blob/master/code/train_interpolation_consistency_training_2D.py) code?
Thanks

**Comment by hritam-98** [comment]
It's similar
